FinalProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('user/', include('user.urls')),
]

news/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:news_id>', views.NewsDetailsView.as_view(), name='details'),
    path('<int:news_id>/del_comment/<int:comment_id>', views.del_comment, name='del_comment'),
    path('mute/<int:user_id>', views.mute, name='mute'),
    path('unmute/<int:user_id>', views.unmute, name='unmute'),
    path('page/<int:page_num>', views.page, name='page'),
    path('add_news/', views.add_news, name='add_news'),
    path('save_news/', views.save_news, name='save_news'),
    path('error/', views.error405, name='error'),
    path('error404/', views.error404, name='error404'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>', views.UserView.as_view(), name='user'),
    path('add_editor/<int:user_id>', views.add_editor, name='add_editor'),
    path('add_moderator/<int:user_id>', views.add_moderator, name='add_moderator'),
    path('del_editor/<int:user_id>', views.del_editor, name='del_editor'),
    path('del_moderator/<int:user_id>', views.del_moderator, name='del_moderator'),
    path('del_news/<int:news_id>', views.del_news, name='del_news'),
    path('hide_news/<int:news_id>', views.hide_news, name='hide_news'),
    path('edit_news/<int:news_id>', views.edit_news, name='edit_news'),
    path('change_avatar/', views.change_avatar, name='change_avatar'),
    path('change_password/', views.change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('auth/', views.AuthView.as_view(), name='auth'),
    path('reg/', views.RegView.as_view(), name='reg'),
    path('logout/', views.log_out, name='logout'),
    path('forget/', views.ForgetView.as_view(), name='forget'),
    path('reset/<str:hashuser>', views.reset, name='reset'),
    path('activate/<str:hashuser>', views.activate, name='activate'),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Extended(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/favicon.jpg')

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_extended(sender, instance, created, **kwargs):
        if created:
            Extended.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_extended(sender, instance, **kwargs):
        instance.extended.save()


class News(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    title = models.CharField(max_length=200)
    prev_text = models.TextField(default='')
    text = models.TextField()
    views = models.IntegerField(default=0)
    image = models.ImageField(blank=True, null=True, default=None, upload_to='media/', height_field=None,
                              width_field=None, max_length=100)
    date = models.DateField(auto_now_add=True)
    hidden = models.BooleanField(default=False)


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    text = models.TextField()
    date = models.DateField(auto_now_add=True)
    news = models.ForeignKey(News, on_delete=models.CASCADE, default=0, related_name='comments')

    def __str__(self):
        return f'{self.user_id} {self.date}'

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class AuthForm(forms.Form):
    login = forms.CharField(max_length=32, min_length=2, label='Логин')
    password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Пароль')


class RegForm(forms.Form):
    email = forms.EmailField(required=True, label='E-mail')
    login = forms.CharField(max_length=32, min_length=2, label='Логин')
    password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Пароль')
    rep_password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Повторите пароль')

    def clean_email(self):
        data = self.cleaned_data
        if len(User.objects.filter(email=data['email'])) == 0:
            return data['email']
        else:
            raise ValidationError("Пользователь с такой почтой уже зарегистрирован")

    def clean_login(self):
        data = self.cleaned_data
        if len(User.objects.filter(username=data['login'])) == 0:
            return data['login']
        else:
            raise ValidationError("Пользователь с таким логином уже зарегистрирован")

    def clean_rep_password(self):
        data = self.cleaned_data
        if data['password'] == data['rep_password']:
            return data['rep_password']
        else:
            raise ValidationError("Пароли не совпадают")

class ForgetForm(forms.Form):
    username = forms.CharField(max_length=32,min_length=2, label = 'Логин')

    def clean_username(self):
        data = self.cleaned_data
        if len(User.objects.filter(username=data['username'])) == 1:
            return data['username']
        else:
            raise ValidationError("Такого пользователя нет")


class ResetForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput,min_length=6, label = 'Пароль')
    rep_password = forms.CharField(widget=forms.PasswordInput,min_length=6, label = 'Повторите пароль')

    def clean_rep_password(self):
        data = self.cleaned_data
        if data['password']==data['rep_password']:
            return data['rep_password']
        else:
            raise ValidationError("Пароли не совпадают")

user/views.py
from .forms import AuthForm, RegForm, ForgetForm, ResetForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic.base import View
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
import datetime
import hashlib
from django.core.mail import send_mail


def print_messages(request, errors):
    for field in errors:
        for error in field.errors:
            messages.error(request, error)


class AuthView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return render(request, 'auth.html', {'signin': AuthForm()})
        else:
            messages.error(request, "Вы уже авторизованы")
            return redirect('news:index')

    def post(self, request, *args, **kwargs):
        auth_user = AuthForm(request.POST)
        if auth_user.is_valid():
            auth_user = auth_user.cleaned_data
            try:
                u = User.objects.get(username=auth_user['login'])
                user = authenticate(request, username=auth_user['login'], password=auth_user['password'])
                if u.is_active:
                    login(request, user)
                    return redirect('news:index')
                else:
                    messages.error(request, "Активируйте аккаунт")
                    return render(request, 'auth.html', {'signin': AuthForm()})
            except:
                messages.error(request, "Пользователя с таким логином и паролем не найдено")
                return render(request, 'auth.html', {'signin': AuthForm()})

        else:
            print_messages(request, auth_user)


class RegView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return render(request, 'reg.html', {'signup': RegForm()})
        else:
            messages.error(request, "Вы уже авторизованы")
            return redirect('news:index')

    def post(self, request, *args, **kwargs):
        reg_user = RegForm(request.POST)
        if reg_user.is_valid():
            reg_user = reg_user.cleaned_data
            user = User.objects.create_user(reg_user['login'], reg_user['email'], reg_user['password'])
            g = Group.objects.get(name="Пользователь")
            g.user_set.add(user)
            hash = hashlib.sha1(user.username.encode('utf-8')).hexdigest()
            send_mail('Активация аккаунта', f'Нажмите: https://latropblog.herokuapp.com/user/activate/{hash}',
                      'csdmmaxplay@gmail.com', [user.email], False)
            user.is_active = False
            user.save()
            messages.info(request, "Вы успешно зарегистрировались.")
        else:
            print_messages(request, reg_user)
        return render(request, 'reg.html', {'signup': RegForm()})


@login_required(login_url='user:auth')
def log_out(request):
    logout(request)
    return redirect('news:index')


class ForgetView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return render(request, 'forget.html', {'forget': ForgetForm})
        else:
            messages.error(request, "Вы уже авторизованы")
            return redirect('news:index')

    def post(self, request, *args, **kwargs):
        user_form = ForgetForm(request.POST)
        if user_form.is_valid():
            user_form = user_form.cleaned_data
            user = User.objects.get(username=user_form['username'])
            hash = hashlib.sha1(user.username.encode('utf-8')).hexdigest()
            send_mail('Забыли пароль', f'Сбросить пароль: https://latropblog.herokuapp.com/user/reset/{hash}',
                      'csdmmaxplay@gmail.com', [user.email], False)
            messages.info(request, 'Проверьте почту')
        else:
            print_messages(request, user_form)
        return redirect('user:forget')


def reset(request, hashuser):
    if not request.user.is_authenticated:
        users = User.objects.filter()
        for user in users:
            if hashuser == hashlib.sha1(user.username.encode('utf-8')).hexdigest():
                if request.method == "POST":
                    reset = ResetForm(request.POST)
                    if reset.is_valid():
                        reset = reset.cleaned_data
                        user.set_password(reset['password'])
                        user.save()
                        messages.info(request, "Пароль успешно изменён")
                        return redirect('news:index')
                    else:
                        print_messages(request, reset)
                return render(request, 'reset.html', {'reset': ResetForm})
        else:
            return redirect('news:error404')
    else:
        messages.error(request, "Вы уже авторизованы")
        return redirect('news:index')


def activate(request, hashuser):
    if not request.user.is_authenticated:
        users = User.objects.filter(is_active=False)
        for user in users:
            if hashuser == hashlib.sha1(user.username.encode('utf-8')).hexdigest():
                user.last_login = datetime.datetime.now()
                user.is_active = True
                user.save()
                messages.info(request, 'Аккаунт активирован')
                return render(request, 'activate.html')
        else:
            messages.error(request, 'Ошибка')
            return render(request, 'activate.html')
    else:
        messages.error(request, 'Вы уже авторизованы')
        return render(request, 'activate.html')

user/templates/activate.html
{% extends 'base.html' %}
{% block title %}
    Активация аккаунта
{% endblock %}

user/templates/auth.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Авторизация
{% endblock %}

{% block body %}
    <div class="info_content">
        <h1 class="title">Авторизация</h1>
        <form method="POST">
            {% csrf_token %}
            {% if signin %}
                {{ signin }}
                <input type="submit" value="Войти" class="btn">{% else %}
            {% endif %}
        </form>
        <a class="link" href="{% url 'user:forget' %}">Забыли пароль?</a>
    </div>
{% endblock %}

user/templates/error.html
{% extends 'base.html' %}
{% block title %}
    Ошибка
{% endblock %}
{% block body %}
    <div class="info_content">
        У вас нет прав
    </div>
{% endblock %}

user/templates/forget.html
{% extends 'base.html' %}
{% block title %}
    Забыли пароль
{% endblock %}
{% block body %}
    <div class="info_content">
        <h1 class="title">Восстоновление пароля</h1>
        {% if forget %}
            <form method="POST">
                {% csrf_token %}
                {{ forget }}
                <input type="submit" value="Отправить" class="btn">
            </form>
        {% endif %}
    </div>
{% endblock %}

user/templates/reg.html
{% extends 'base.html' %}
{% block title %}
    Регистрация
{% endblock %}
{% block body %}
    <div class="info_content">
        <h1 class="title">Регистрация</h1>
        <form method="POST">
            {% csrf_token %}
            {% if signup %}
                {{ signup }}
                <input type="submit" value="Зарегистрироваться" class="btn">
            {% endif %}
        </form>
    </div>
{% endblock %}

user/templates/reset.html
{% extends 'base.html' %}
{% block title %}
    Сброс пароля
{% endblock %}
{% block body %}
    <div class="info_content">
        <h1 class="title">Сброс пароля</h1>
        <form method="POST">
            {% csrf_token %}
            {% if reset %}
                {{ reset }}
                <input type="submit" value="Изменить" class="btn">
            {% endif %}
        </form>
    </div>
{% endblock %}

user/templates/user.html
{% extends 'base.html' %}
{% block title %}
    Пользователь {{ usr.username }}
{% endblock %}
{% block body %}
    {% if user.is_authenticated and usr %}
        Id: {{ usr.id }}<br>
        Login: {{ usr.username }}<br>
        Дата регистрации: {{ user.date_joined }}<br>
        Group:
        {% if usr.is_superuser %}
            Админ
        {% endif %}
        {% for i in group %}
            {{ i }}
        {% endfor %}<br>
        <div class="perms">
            {% if not usr.id == user.id  and not usr.is_superuser and not usr.delete_user %}
                {% if perms.news.delete_comments %}
                    <a href="{% url 'news:mute' usr.id %}">Замутить пользователя</a><br>
                    <a href="{% url 'news:unmute' usr.id %}">Размутить пользователя</a><br>
                {% endif %}
            {% endif %}
            {% if user.is_superuser and user.id != usr.id %}
                <a href="{% url 'news:add_editor' usr.id %}">Сделать редактором</a><br>
                <a href="{% url 'news:del_editor' usr.id %}">Забрать права редактора</a><br>
                <a href="{% url 'news:add_moderator' usr.id %}">Сделать модератором</a><br>
                <a href="{% url 'news:del_moderator' usr.id %}">Забрать права модератора</a><br>
            {% endif %}
        </div>
    {% else %}
        Авторизируйтесь
    {% endif %}
{% endblock %}