FinalProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('user/', include('user.urls')),
]

news/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "news"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:news_id>', views.NewsDetailsView.as_view(), name='details'),
    path('<int:news_id>/del_comment/<int:comment_id>', views.del_comment, name='del_comment'),
    path('mute/<int:user_id>', views.mute, name='mute'),
    path('unmute/<int:user_id>', views.unmute, name='unmute'),
    path('page/<int:page_num>', views.page, name='page'),
    path('add_news/', views.add_news, name='add_news'),
    path('save_news/', views.save_news, name='save_news'),
    path('error/', views.error405, name='error'),
    path('error404/', views.error404, name='error404'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>', views.UserView.as_view(), name='user'),
    path('add_editor/<int:user_id>', views.add_editor, name='add_editor'),
    path('add_moderator/<int:user_id>', views.add_moderator, name='add_moderator'),
    path('del_editor/<int:user_id>', views.del_editor, name='del_editor'),
    path('del_moderator/<int:user_id>', views.del_moderator, name='del_moderator'),
    path('del_news/<int:news_id>', views.del_news, name='del_news'),
    path('hide_news/<int:news_id>', views.hide_news, name='hide_news'),
    path('edit_news/<int:news_id>', views.edit_news, name='edit_news'),
    path('change_avatar/', views.change_avatar, name='change_avatar'),
    path('change_password/', views.change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('auth/', views.AuthView.as_view(), name='auth'),
    path('reg/', views.RegView.as_view(), name='reg'),
    path('logout/', views.log_out, name='logout'),
    path('forget/', views.ForgetView.as_view(), name='forget'),
    path('reset/<str:hashuser>', views.reset, name='reset'),
    path('activate/<str:hashuser>', views.activate, name='activate'),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Extended(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/favicon.jpg')

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_extended(sender, instance, created, **kwargs):
        if created:
            Extended.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_extended(sender, instance, **kwargs):
        instance.extended.save()


class News(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    title = models.CharField(max_length=200)
    prev_text = models.TextField(default='')
    text = models.TextField()
    views = models.IntegerField(default=0)
    image = models.ImageField(blank=True, null=True, default=None, upload_to='media/', height_field=None,
                              width_field=None, max_length=100)
    date = models.DateField(auto_now_add=True)
    hidden = models.BooleanField(default=False)


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    text = models.TextField()
    date = models.DateField(auto_now_add=True)
    news = models.ForeignKey(News, on_delete=models.CASCADE, default=0, related_name='comments')

    def __str__(self):
        return f'{self.user_id} {self.date}'

user/models.py
from django.db import models

# Create your models here.

news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class AvatarForm(forms.Form):
    image = forms.FileField(label='Аватар')

    def clean_image(self):
        data = self.cleaned_data
        print(data['image'])
        if not (data['image'].name.endswith('.gif') or data['image'].name.endswith('.jpg') or
                data['image'].name.endswith('.jpeg') or data['image'].name.endswith('.png')):
            raise ValidationError("Загружать можно только изображения. Поддерживаемые расширения: .gif/.png/.jpg/.jpeg")
        else:
            return data['image']


class CommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea, label='Оставить комментарий')


class EditPasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Текущий пароль')
    new_password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Новый пароль')
    rep_new_password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Повторите пароль')

    def clean_rep_new_password(self):
        data = self.cleaned_data
        if data['rep_new_password'] == data['new_password']:
            if data['old_password'] != data['new_password']:
                return data['new_password']
            else:
                raise ValidationError("Нельзя изменить пароль на текущий")
        else:
            raise ValidationError("Пароли не совпадают")


class AddNewsForm(forms.Form):
    title = forms.CharField(max_length=200, label='Заголовок')
    prev_text = forms.CharField(widget=forms.Textarea, label='Превью текст')
    text = forms.CharField(widget=forms.Textarea, label='Основной текст')
    image = forms.FileField(label='Изображение')

    def clean_image(self):
        data = self.cleaned_data
        if not (data['image'].name.endswith('.gif') or data['image'].name.endswith('.jpg') or
                data['image'].name.endswith('.jpeg') or data['image'].name.endswith('.png')):
            raise ValidationError("Загружать можно только изображения. Поддерживаемые расширения: .gif/.png/.jpg/.jpeg")
        else:
            return data['image']

news/views.py
from .models import News, Comments
from .forms import CommentForm, EditPasswordForm, AddNewsForm, AvatarForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group

COUNT = 4


def print_messages(request, errors):
    for field in errors:
        for error in field.errors:
            messages.error(request, error)


def index(request):
    page_num = 0
    query = list(reversed(News.objects.filter()))
    if not request.user.has_perm('news.view_hidden_news'):
        query = [item for item in query if not item.hidden]
    lst = reversed(query[page_num * COUNT: (page_num + 1) * COUNT:1])
    context = {'news': lst}
    if not (page_num + 1) * COUNT >= len(query):
        context['forward'] = page_num + 1
    return render(request, 'index.html', context)


def page(request, page_num):
    query = list(reversed(News.objects.filter()))
    if not request.user.has_perm('news.view_hidden_news'):
        query = [item for item in query if not item.hidden]
    lst = reversed(query[page_num * COUNT: (page_num + 1) * COUNT:1])
    context = {'news': lst}
    if not page_num - 1 == -1:
        context['back'] = str(page_num - 1)
    if not (page_num + 1) * COUNT >= len(query):
        context['forward'] = page_num + 1
    return render(request, 'index.html', context)


class NewsDetailsView(View):
    def get(self, request, *args, **kwargs):
        try:
            news_item = News.objects.get(id=kwargs['news_id'])
        except:
            return redirect('news:error404')
        if news_item.hidden:
            if not request.user.has_perm('news.view_hidden_news'):
                return redirect('news:error404')
        news_item.views = news_item.views + 1
        news_item.save()
        return render(request, 'details.html', {"news_item": news_item, 'form': CommentForm()})

    def post(self, request, *args, **kwargs):
        if request.user.has_perm('news.add_comments'):
            comment = CommentForm(request.POST)
            if comment.is_valid():
                comment = comment.cleaned_data
                new_comment = Comments(user_id=request.user.id, text=comment['text'], news_id=kwargs['news_id'])
                new_comment.save()
        else:
            messages.error(request, 'Вы не можете оставлять комментарии')
        return redirect('news:details', kwargs['news_id'])


@login_required(login_url='user:auth')
def change_avatar(request):
    if request.method == "POST":
        user = User.objects.get(id=request.user.id)
        avatar_form = AvatarForm(request.POST, request.FILES)
        if avatar_form.is_valid():
            avatar_form = avatar_form.cleaned_data
            user.extended.avatar = avatar_form['image']
            user.save()
            messages.info(request, 'Изображение успешно загружено')
        else:
            print_messages(request, avatar_form)
    return redirect('news:profile')


@login_required(login_url='user:auth')
def change_password(request):
    if request.method == "POST":
        user = User.objects.get(id=request.user.id)
        username = user.username
        edit_password_form = EditPasswordForm(request.POST)
        if edit_password_form.is_valid():
            edit_password_form = edit_password_form.cleaned_data
            if not (check_password(edit_password_form['old_password'], user.password)):
                messages.error(request, "Неверный пароль")
            else:
                user.set_password(edit_password_form['new_password'])
                user.save()
                messages.info(request, "Пароль успешно изменён")
                user = authenticate(request, username=username, password=edit_password_form['new_password'])
                login(request, user)
        else:
            print_messages(request, edit_password_form)
    return redirect('news:profile')


@login_required(login_url='user:auth')
def profile(request):
    return render(request, 'profile.html',
                  {"group": request.user.groups.all(), 'edit_password': EditPasswordForm(),
                   'avatar': AvatarForm()})


@permission_required('news.hide_news', login_url='news:error')
def hide_news(request, news_id):
    try:
        news_item = News.objects.get(id=news_id)
    except:
        return redirect('news:error404')
    if news_item.hidden:
        messages.info(request, "Новость успешно показана")
    else:
        messages.info(request, "Новость успешно скрыта")
    news_item.hidden = not news_item.hidden
    news_item.save()
    return redirect('news:index')


@permission_required('news.edit_news', login_url='news:error')
def edit_news(request, news_id):
    if request.method == "POST":
        news = AddNewsForm(request.POST, request.FILES)
        if news.is_valid():
            news = news.cleaned_data
            ns = News.objects.get(id=news_id)
            ns.text = news['text']
            ns.title = news['title']
            ns.prev_text = news['prev_text']
            ns.image = news['image']
            ns.save()
            messages.info(request, "Новость изменена")
        else:
            print_messages(request, news)
    news = News.objects.get(id=news_id)
    edit_form = AddNewsForm(
        initial={'title': news.title, 'text': news.text, 'prev_text': news.prev_text, 'image': news.image})
    return render(request, 'edit_news.html', {'edit_news': edit_form})


@permission_required('news.delete_news', login_url='news:error')
def del_news(request, news_id):
    try:
        News.objects.get(id=news_id).delete()
    except:
        return redirect('news:error404')
    messages.info(request, "Новость успешно удалёна")
    return redirect('news:index')


@permission_required('news.delete_comments', login_url='news:error')
def del_comment(request, news_id, comment_id):
    try:
        Comments.objects.get(id=comment_id).delete()
    except:
        return redirect('news:error404')
    messages.info(request, "Комментарий успешно удалён")
    return redirect(f'/{news_id}')


@permission_required('auth.mute', login_url='news:error')
def mute(request, user_id):
    try:
        u = User.objects.get(id=user_id)
    except:
        return redirect('news:error404')
    if u.has_perm('news.add_comments'):
        g = Group.objects.get(name="Пользователь")
        g.user_set.remove(u)
        messages.info(request, "Пользователь успешно замучен")
    return redirect('news:user', user_id)


@permission_required('auth.unmute', login_url='news:error')
def unmute(request, user_id):
    try:
        u = User.objects.get(id=user_id)
    except:
        return redirect('news:error404')
    if not u.has_perm('news.add_comments'):
        g = Group.objects.get(name="Пользователь")
        g.user_set.add(u)
        messages.info(request, "Пользователь успешно размучен")
    return redirect('news:user', user_id)


@permission_required('auth.add_group', login_url='news:error')
def add_editor(request, user_id):
    if request.user.is_superuser:
        try:
            user = User.objects.get(id=user_id)
        except:
            return redirect('news:error404')
        group = Group.objects.get(name="Редактор")
        group.user_set.add(user)
        messages.info(request, "Пользователю добавлены возможности редактора")
        return redirect('news:user', user_id)
    else:
        return redirect('news:error')


@permission_required('auth.add_group', login_url='news:error')
def add_moderator(request, user_id):
    if request.user.is_superuser:
        try:
            user = User.objects.get(id=user_id)
        except:
            return redirect('news:error404')
        g = Group.objects.get(name="Модератор")
        g.user_set.add(user)
        messages.info(request, "Пользователю добавлены возможности модератора")
        return redirect('news:user', user_id)
    else:
        return redirect('news:error')


@permission_required('auth.delete_group', login_url='news:error')
def del_editor(request, user_id):
    if request.user.is_superuser:
        try:
            user = User.objects.get(id=user_id)
        except:
            return redirect('news:error404')
        g = Group.objects.get(name="Редактор")
        g.user_set.remove(user)
        messages.info(request, "Права редактора удалены")
        return redirect('news:user', user_id)
    else:
        return redirect('news:error')


@permission_required('auth.delete_group', login_url='news:error')
def del_moderator(request, user_id):
    if request.user.is_superuser:
        try:
            user = User.objects.get(id=user_id)
        except:
            return redirect('news:error404')
        g = Group.objects.get(name="Модератор")
        g.user_set.remove(user)
        messages.info(request, "Права модератора удалены")
        return redirect('news:user', user_id)
    else:
        return redirect('news:error')


@permission_required('news.add_news', login_url='news:error')
def save_news(request):
    if request.method == "POST":
        add_news = AddNewsForm(request.POST, request.FILES)
        if add_news.is_valid():
            add_news = add_news.cleaned_data
            ns = News(title=add_news['title'], text=add_news['text'], author_id=request.user.id,
                      image=add_news['image'], prev_text=add_news['prev_text'])
            ns.save()
            messages.info(request, "Новость опубликована")
        else:
            print_messages(request, add_news)
    return redirect('news:add_news')


@permission_required('news.add_news', login_url='news:error')
def add_news(request):
    return render(request, 'addnews.html', {'add_news': AddNewsForm()})


class UserView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:

news/templates/405.html
{% extends 'base.html' %}
{% block title %}
    Ошибка
{% endblock %}
{% block body %}

    <div class="info_content">
        <h1 class="title">У вас нет прав</h1>
    </div>
{% endblock %}

news/templates/addnews.html
{% extends 'base.html' %}
{% block title %}
    Добавить новость
{% endblock %}
{% block body %}
    <div class="info_content">
        <h1 class="title">Добавить новость</h1>
        {% if perms.news.add_news %}
            <form method="POST" action="{% url 'news:save_news' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ add_news }}
                <input class="btn" type="submit" value="Запостить">
            </form>
        {% endif %}
    </div>
{% endblock %}

news/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/static/img/icons/favicon.ico">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="wrap">
    <div id="menu">
        {% if not user.is_authenticated %}
            <a href="{% url 'user:auth' %}">Авторизация</a>
            <a href="{% url 'user:reg' %}">Регистрация</a>
        {% else %}
            <div class="avatar">
                <div class="img_container">
                    <img src="http://latropblog.herokuapp.com/media/{{ user.extended.avatar }}" alt="{{ user.username }}">
                </div>
            </div>
            <span class="username">{{ user.username }}</span>
            <a class="profile" href="{% url 'news:profile' %}">Профиль</a>
            <a class="logout" href="{% url 'user:logout' %}">Выйти</a>
        {% endif %}
        <a class="dev" href="https://github.com/LatropAgency">Разработчик</a>
        <span class="phone">+375297441171</span>
    </div>
    <div class="content">
        <div id="menu_btn">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <header>
            <div class="header_topline">
                <a class="my_blog" href="{% url 'news:index' %}">My blog</a>
                <div class="soc">
                    <a href="#"><img src="/static/img/icons/twitter.svg" alt="twitter"></a>
                    <a href="#"><img src="/static/img/icons/telegram.svg" alt="telegram"></a>
                    <a href="https://vk.com/csdmmaxplay"><img src="/static/img/icons/vk.svg" alt="vk"></a>
                    <a href="https://www.instagram.com/vovakolesnikovich/"><img src="/static/img/icons/instagram.svg"
                                                                                alt="instagram"></a>
                </div>
            </div>
        </header>
        <div id="notifications">
            {% block notifications %}
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endblock %}
        </div>
        {% block body %}
        {% endblock %}
        <footer>
            ©All rights reserved. Design: Veronika
        </footer>
    </div>
</div>
<script src="/static/js/common.js"></script>
</body>
</html>

news/templates/details.html
{% extends 'base.html' %}
{% block title %}
    {% if news_item %}
        {{ news_item.title }}
    {% endif %}
{% endblock %}
{% block body %}
    {% if news_item %}
        <div class="news_item">
        <img src="media/{{ news_item.image }}">
        <div class="info_item">
        <div class="info">
            <div class="date">{{ news_item.date }}</div>
            <div class="views">{{ news_item.views }}</div>
        </div>
        <h1 class="title">{{ news_item.title }}</h1>
        <p class="text">{{ news_item.text }}</p>
        <span>Автор: <a class="link"
                        href="{% url 'news:user' news_item.author.id %}">{{ news_item.author.username }}</a></span>

        {% if user.is_authenticated and perms.news.add_comments %}
            <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Готово" class="btn">
        {% else %}
            <br>Вы не можете добавлять комментарии
        {% endif %}
    <h4>Комментарии:</h4>
    {% for comment_item in news_item.comments.all reversed %}
        <div class="comment">
            <img src="http://latropblog.herokuapp.com/media/{{ comment_item.user.extended.avatar }}"
                 alt="{{ comment_item.user.username }}">
            <div class="comment_info">
                <a class="link" href="{% url 'news:user' comment_item.user.id %}">{{ comment_item.user.username }}</a>
                <p> {{ comment_item.text }}</p>
                <div class="perms">
                    <span class="date">{{ comment_item.date }}</span>
                    {% if perms.news.delete_comments and not comment_item.user.is_superuser or user.is_superuser %}
                        <a href="{% url  'news:del_comment' news_item.id comment_item.id %}">Удалить
                            комментарий</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    </form>
    {% endif %}
</div>
</div>
{% endblock %}

news/templates/edit_news.html
{% extends 'base.html' %}
{% block title %}
    Редактировать новость
{% endblock %}
{% block body %}
    <div class="info_content">
        <h1 class="title">Редактировать новость</h1>
        {% if edit_news and perms.news.edit_news %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ edit_news }}
                <input class="btn" type="submit" value="Сохранить">
            </form>
        {% endif %}
    </div>
{% endblock %}

news/templates/error.html
{% extends 'base.html' %}
{% block title %}
    Ошибка
{% endblock %}
{% block body %}

    <div class="info_content">
        <h1 class="title">У вас нет прав</h1>
    </div>
{% endblock %}

news/templates/index.html
{% extends 'base.html' %}
{% block title %}
    Главная
{% endblock %}
{% block body %}
    <div class="news">
        {% for news_item in news reversed %}
            {% if perms.news.view_hidden_news or not news_item.hidden %}
                <div class="news_item {% if news_item.hidden %}hidden{% endif %}">
                    <div class="img_container">
                        <img src="http://latropblog.herokuapp.com/media/{{ news_item.image }}">
                    </div>
                    <div class="info_item">
                        <div class="info">
                            <div class="date">{{ news_item.date }}</div>
                            <div class="views">{{ news_item.views }}</div>
                        </div>
                        <a href="{% url 'news:details' news_item.id %}" class="title">{{ news_item.title }}</a>
                        <p class="prev_text">{{ news_item.prev_text }}</p>
                        <a class="btn" href="{% url 'news:details' news_item.id %}">Читать</a>
                        {% if perms.news.edit_news %}
                            <a class="btn" href="{% url 'news:edit_news' news_item.id %}">Редактировать</a>
                        {% endif %}
                        {% if perms.news.delete_news %}
                            <a class="btn" href="{% url 'news:del_news' news_item.id %}">Удалить</a>
                        {% endif %}
                        {% if not news_item.hidden  and perms.news.hide_news %}
                            <a class="btn" href="{% url 'news:hide_news' news_item.id %}">Скрыть</a>
                        {% endif %}
                        {% if news_item.hidden  and perms.news.hide_news %}
                            <a class="btn" href="{% url 'news:hide_news' news_item.id %}">Показать</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="navigation">
        {% if back %}
            <a class="btn" href="{% url 'news:page' back %}">Назад</a>
        {% endif %}
        {% if forward %}
            <a class="btn" href="{% url 'news:page' forward %}">Далее</a>
        {% endif %}
    </div>
{% endblock %}

news/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Профиль
{% endblock %}
{% block body %}
    <div class="info_content">
        <h1 class="title">Профиль</h1>
        <div class="profile_wrap">
            <div class="avatar">
                <img src="http://latropblog.herokuapp.com/media/{{ user.extended.avatar }}" alt="{{ user.username }}">
                <form method="POST" enctype="multipart/form-data" action="{% url 'news:change_avatar' %}">
                    {% csrf_token %}
                    {{ avatar }}
                    <input type="submit" value="Загрузить" class="btn">
                </form>
            </div>
            <div class="profile_info">
                <span>Id: {{ user.id }}</span>
                <span>Логин: {{ user.username }}</span>
                <span>E-mail: {{ user.email }}</span>
                <span>Дата регистрации: {{ user.date_joined }}</span>
                {% for i in group %}
                    {{ i.name }}
                {% endfor %}
                {% if perms.news.add_news %}
                    <a class="btn" href="{% url 'news:add_news' %}">Добавить новость</a>
                {% endif %}
            </div>
        </div>
        <h2 class="title">Смена пароля</h2>
        <hr>
        <form class="edit_pass" method="POST" action="{% url 'news:change_password' %}">
            {% csrf_token %}
            {{ edit_password }}
            <input type="submit" value="Изменить" class="btn">
        </form>
    </div>
{% endblock %}

news/templates/user.html
{% extends 'base.html' %}
{% block title %}
    Пользователь {{ usr.username }}
{% endblock %}
{% block body %}
    <div class="info_content">
        <h1 class="title">Профиль</h1>
        <div class="profile_wrap">
            {% if user.is_authenticated and usr %}
                <div class="avatar">
                    <img src="http://latropblog.herokuapp.com/media/{{ usr.extended.avatar }}" alt="{{ usr.username }}">
                </div>
                <div class="profile_info">
                    <span>Id: {{ usr.id }}</span>
                    <span>Login: {{ usr.username }}</span>
                    <span>Дата регистрации: {{ user.date_joined }}</span>
                    <span>Group:
                        {% if usr.is_superuser %}
                            Админ
                        {% endif %}
                        {% for i in group %}
                            {{ i }}
                        {% endfor %}
                    </span>
                </div>
                </div>
                <div class="perms">
                    {% if not usr.id == user.id  and not usr.is_superuser %}
                        {% if perms.auth.mute and perms.auth.unmute %}
                            {% if u %}
                                <a href="{% url 'news:mute' usr.id %}">Замутить пользователя</a><br>
                            {% else %}
                                <a href="{% url 'news:unmute' usr.id %}">Размутить пользователя</a><br>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    {% if user.is_superuser and user.id != usr.id %}
                            {% if editor %}
                                <a href="{% url 'news:del_editor' usr.id %}">Забрать права редактора</a><br>
                            {% else %}
                                <a href="{% url 'news:add_editor' usr.id %}">Сделать редактором</a><br>
                            {% endif %}
                            {% if moderator %}
                                <a href="{% url 'news:del_moderator' usr.id %}">Забрать права модератора</a><br>
                            {% else %}
                                <a href="{% url 'news:add_moderator' usr.id %}">Сделать модератором</a><br>
                            {% endif %}
                    {% endif %}
                </div>
                </div>
            {% endif %}
{% endblock %}